#!/bin/bash 

COMPLETE=0

BASEURL='https://www.ss.lv'
PARTURL='/lv/transport/cars/sell/filter/riga_f/'
FURL=$BASEURL$PARTURL
FIRST=$FURL

LIST=.raw

touch $LIST

echo $BASEURL
echo $FURL

#echo $FILEN

#exit 0

while [  $COMPLETE -eq 0 ]; do

    FILEN=$(echo $FURL | rev | cut -d '/' -f 1 | rev)

    curl $FURL -H 'Host: www.ss.lv' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Referer: https://www.ss.lv/lv/transport/cars/sell/filter/riga_f/' -H 'Cookie: PHPSESSID=; sid=; LG=lv; _ga=' -H 'Connection: keep-alive' -H 'Cache-Control: max-age=0' -o "$FILEN" && \
tempPARTURL=$(grep "rel=\"next\" class=\"navi\"" "$FILEN" | sed 's/</\n</g' | grep ">N" | cut -d '"' -f 8)

    if [ "$FIRST" == "$BASEURL$tempPARTURL" ]; then

        echo "last link found"

        let COMPLETE=1

    else

       PARTURL="$tempPARTURL"
       FURL=$BASEURL$PARTURL

       mv "$LIST" "$LIST.tmp"
       cat "$LIST.tmp" "$FILEN" > "$LIST"
       rm "$LIST.tmp"

       echo "next to check $FURL"
        
    fi

    #let COMPLETE=1

done

#vim:ts=4
